language: php
dist: trusty
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - nightly

before_script:
  - composer install --dev --prefer-source

script: ./vendor/bin/phpunit --coverage-text